NumPy --> Numerical Python


Advantages:
1.Allows several Mathematical Operations
2.Faster Operations

In [2]:
import numpy as np

#### List Vs Numpy time taken

In [5]:
from time import process_time

In [9]:
#time take by a list
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [11]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0


#### NumPy Arrays

In [12]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [14]:
# creating a one dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a.shape

(4,)

In [18]:
b = np.array([(5,6,7,8),(1,2,3,4)])
print(b)

[[5 6 7 8]
 [1 2 3 4]]


In [19]:
b.shape

(2, 4)

In [20]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#### Intial PlaceHolders in numpy arrays

In [2]:
#create numpy array of zeros
import numpy as np
x = np.zeros((4,5))

In [3]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
#create numpy array of one
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
#create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#create an numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.11029638 0.57374526 0.09449951 0.58056841]
 [0.56378375 0.43527489 0.72390182 0.47632302]
 [0.49527867 0.36082403 0.56120181 0.07737647]]


In [9]:
#create an numpy array with random integers within specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[78 68 52 10 51]
 [13 66 87 88 32]
 [80 70 19 46 58]]


In [10]:
#array of evenly spaced value -----> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [11]:
#array of evenly spaced value ------> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [12]:
#convert a list to an array
list2 =[10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [13]:
# Analysing a numpy array
c = np.random.randint(10,90,(5,5))
print(c)

[[19 77 80 63 68]
 [53 34 45 34 76]
 [52 65 74 11 89]
 [33 23 70 57 23]
 [89 16 14 38 88]]


In [14]:
#array dimension
print(c.shape)

(5, 5)


In [15]:
# no of dimension
print(c.ndim)

2


In [16]:
# checking the number of elements in an array
print(c.size)

25


In [18]:
# checking datatype of values in the array
print(c.dtype)

int32


#### Mathematical Operation on numpy array

In [19]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[6 5 3]
 [5 6 0]
 [7 6 9]]
[[15 18 10]
 [18 19 15]
 [12 13 17]]


In [5]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 23 13]
 [23 25 15]
 [19 19 26]]
[[ -9 -13  -7]
 [-13 -13 -15]
 [ -5  -7  -8]]
[[ 90  90  30]
 [ 90 114   0]
 [ 84  78 153]]
[[0.4        0.27777778 0.3       ]
 [0.27777778 0.31578947 0.        ]
 [0.58333333 0.46153846 0.52941176]]


In [6]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [7]:
print(a)
print(b)

[[2 0 2]
 [0 4 2]
 [8 5 4]]
[[17 15 13]
 [19 15 12]
 [11 14 16]]


In [8]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 15 15]
 [19 19 14]
 [19 19 20]]
[[-15 -15 -11]
 [-19 -11 -10]
 [ -3  -9 -12]]
[[34  0 26]
 [ 0 60 24]
 [88 70 64]]
[[0.11764706 0.         0.15384615]
 [0.         0.26666667 0.16666667]
 [0.72727273 0.35714286 0.25      ]]


#### Array Manpulation

In [10]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 3 2]
 [0 3 3]]
(2, 3)


In [11]:
#transpose
trans = np.transpose(a)
print(trans)
print(trans.shape)

[[8 0]
 [3 3]
 [2 3]]
(3, 2)


In [12]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 8 9]
 [9 3 1]]
(2, 3)


In [13]:
b = a.T
print(b)
print(b.shape)

[[8 9]
 [8 3]
 [9 1]]
(3, 2)


In [14]:
#reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 0 8]
 [5 2 4]]
(2, 3)


In [15]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 0]
 [8 5]
 [2 4]]
(3, 2)
